@REVALIDATE_SECRET=<random-string>
@REVALIDATE_URL=http://localhost:3000/api/revalidate
@REVALIDATE_URL_LIVE=https://www.familogue.ca/api/revalidate
###
POST {{REVALIDATE_URL}}
X-Revalidate-Token: {{REVALIDATE_SECRET}}
Content-Type: application/json